default: &default
  adapter: mysql2
  encoding: utf8
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DATABASE_USER') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  port: 3306

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') %>


